// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebCapacitacionSacdeYluz.Data;

#nullable disable

namespace WebCapacitacionSacdeYluz.Data.Migrations
{
    [DbContext(typeof(WebCapacitacionSacdeLuzDbContext))]
    partial class WebCapacitacionSacdeLuzDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebCapacitacionSacdeYluz.Data.Models.DwdCalzado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MarcaId")
                        .HasColumnType("int");

                    b.Property<string>("Modelo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Precio")
                        .HasColumnType("float");

                    b.Property<int>("Talle")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MarcaId");

                    b.ToTable("DwdCalzado", (string)null);
                });

            modelBuilder.Entity("WebCapacitacionSacdeYluz.Data.Models.DwdMarca", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pais")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DwdMarca", (string)null);
                });

            modelBuilder.Entity("WebCapacitacionSacdeYluz.Data.Models.DwdProveedor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Comision")
                        .HasColumnType("float");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DwdProveedor", (string)null);
                });

            modelBuilder.Entity("WebCapacitacionSacdeYluz.Data.Models.DwdTienda", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Direccion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Provincia")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DwdTienda", (string)null);
                });

            modelBuilder.Entity("WebCapacitacionSacdeYluz.Data.Models.DwdVendedor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TiendaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TiendaId");

                    b.ToTable("DwdVendedor", (string)null);
                });

            modelBuilder.Entity("WebCapacitacionSacdeYluz.Data.Models.DwfCompra", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("FechaCompra")
                        .HasColumnType("datetime2");

                    b.Property<double>("Ganancia")
                        .HasColumnType("float");

                    b.Property<int>("ProveedorId")
                        .HasColumnType("int");

                    b.Property<int>("TiendaId")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("ProveedorId");

                    b.HasIndex("TiendaId");

                    b.ToTable("DwfCompra", (string)null);
                });

            modelBuilder.Entity("WebCapacitacionSacdeYluz.Data.Models.DwfCompraXCalzado", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("CalzadoId")
                        .HasColumnType("int");

                    b.Property<int>("CompraId")
                        .HasColumnType("int");

                    b.Property<int>("cantidad")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("CalzadoId");

                    b.HasIndex("CompraId");

                    b.ToTable("DwfCompraXCalzado", (string)null);
                });

            modelBuilder.Entity("WebCapacitacionSacdeYluz.Data.Models.DwfTiendaXCalzado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CalzadoId")
                        .HasColumnType("int");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.Property<int>("TiendaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CalzadoId");

                    b.HasIndex("TiendaId");

                    b.ToTable("DwfTiendaXCalzado", (string)null);
                });

            modelBuilder.Entity("WebCapacitacionSacdeYluz.Data.Models.DwfVentas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FechaPago")
                        .HasColumnType("datetime2");

                    b.Property<int>("VendedorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VendedorId");

                    b.ToTable("DwfVentas", (string)null);
                });

            modelBuilder.Entity("WebCapacitacionSacdeYluz.Data.Models.DwfVentasXCalzado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CalzadoId")
                        .HasColumnType("int");

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<int>("VentasId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CalzadoId");

                    b.HasIndex("VentasId");

                    b.ToTable("DwfVentasXCalzados", (string)null);
                });

            modelBuilder.Entity("WebCapacitacionSacdeYluz.Data.Models.DwdCalzado", b =>
                {
                    b.HasOne("WebCapacitacionSacdeYluz.Data.Models.DwdMarca", "Marca")
                        .WithMany()
                        .HasForeignKey("MarcaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Marca");
                });

            modelBuilder.Entity("WebCapacitacionSacdeYluz.Data.Models.DwdVendedor", b =>
                {
                    b.HasOne("WebCapacitacionSacdeYluz.Data.Models.DwdTienda", "Tienda")
                        .WithMany()
                        .HasForeignKey("TiendaId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Tienda");
                });

            modelBuilder.Entity("WebCapacitacionSacdeYluz.Data.Models.DwfCompra", b =>
                {
                    b.HasOne("WebCapacitacionSacdeYluz.Data.Models.DwdProveedor", "Proveedor")
                        .WithMany()
                        .HasForeignKey("ProveedorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebCapacitacionSacdeYluz.Data.Models.DwdTienda", "Tienda")
                        .WithMany()
                        .HasForeignKey("TiendaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Proveedor");

                    b.Navigation("Tienda");
                });

            modelBuilder.Entity("WebCapacitacionSacdeYluz.Data.Models.DwfCompraXCalzado", b =>
                {
                    b.HasOne("WebCapacitacionSacdeYluz.Data.Models.DwdCalzado", "Calzado")
                        .WithMany()
                        .HasForeignKey("CalzadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebCapacitacionSacdeYluz.Data.Models.DwfCompra", "Compra")
                        .WithMany()
                        .HasForeignKey("CompraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Calzado");

                    b.Navigation("Compra");
                });

            modelBuilder.Entity("WebCapacitacionSacdeYluz.Data.Models.DwfTiendaXCalzado", b =>
                {
                    b.HasOne("WebCapacitacionSacdeYluz.Data.Models.DwdCalzado", "Calzado")
                        .WithMany()
                        .HasForeignKey("CalzadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebCapacitacionSacdeYluz.Data.Models.DwdTienda", "Tienda")
                        .WithMany()
                        .HasForeignKey("TiendaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Calzado");

                    b.Navigation("Tienda");
                });

            modelBuilder.Entity("WebCapacitacionSacdeYluz.Data.Models.DwfVentas", b =>
                {
                    b.HasOne("WebCapacitacionSacdeYluz.Data.Models.DwdVendedor", "Vendedor")
                        .WithMany()
                        .HasForeignKey("VendedorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vendedor");
                });

            modelBuilder.Entity("WebCapacitacionSacdeYluz.Data.Models.DwfVentasXCalzado", b =>
                {
                    b.HasOne("WebCapacitacionSacdeYluz.Data.Models.DwdCalzado", "Calzado")
                        .WithMany()
                        .HasForeignKey("CalzadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebCapacitacionSacdeYluz.Data.Models.DwfVentas", "Ventas")
                        .WithMany()
                        .HasForeignKey("VentasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Calzado");

                    b.Navigation("Ventas");
                });
#pragma warning restore 612, 618
        }
    }
}
